### ISSUE TITLE
Link ABM GAMA Simulation and UDViz

### ISSUE THREAD

**Issue by agrignard** [VCityTeam/UD_ReAgent_ABM#1]
This is issue is meant to have discussion related to the implement a first version of a GAMA simulation export that could be visualised in UD_Viz using the DeckGL framework.

So far, a simple random walk on the presqu'ile has been implemented in GAMA as an Hello World, and the results of the simulation is stored here
https://github.com/VCityTeam/UD_ReAgent_ABM/blob/master/ReAgent/models/result.json

Ideally this file should be visualized in UD_Viz as a DeckGL container.

@CorentinGaut and @vmachado are currently working on the integration of DeckGl inside UD_Viz, here (https://github.com/VCityTeam/UD-Viz/tree/deckgl)

WIP and finger crossed ;-)!

**Comment by agrignard** [comment]
@CorentinGaut can we agree and what to produce? 

What about 100 agents with 100 steps for now?

**Comment by agrignard** [comment]
@CorentinGaut do we have any update on this issue? Would it be possible to have a link to a UD_VIz viewer if it exists.

We have made several iteration on the deckgl file here (https://github.com/VCityTeam/UD_ReAgent_ABM/blob/master/ReAgent/models/result.json) , do you need any further information?  Is the projection ok?

**Comment by CorentinGaut** [comment]
This projection format is compatible with UD-VIZ but not for DeckGL Library, to compute 3DTiles there is no problem.

**Comment by agrignard** [comment]
Ok I see, then which  one should we use for DeckGL? It would be great to find a projection that fits for everyone.

What about using WGS84 for all of us? Not precise enough I guess for Lyon?

**Comment by agrignard** [comment]
I close this issue as the deckGL method has not been chosen and successfully implemented. Work is now done on this path #11
