### ISSUE TITLE
Region of Interest for the Site

### ISSUE THREAD

**Issue by agrignard** [VCityTeam/UD_ReAgent_ABM#3]
We have to define together the right ROI (region of interest for the project). From now on we don't have yet a georeference map of the site so we need to produce it by ourself.

@johnsamuelwrites and @DiegoVinasco can you let me know the information you need in order to exctract the cityGML.

I have created here https://github.com/VCityTeam/UD_ReAgent_ABM/blob/master/ReAgent/includes/GratteCiel/Bounds.shp a rectangle that "fits" but using my eye with this picture (taken from my phone)

<img width="484" alt="enveloppe" src="https://user-images.githubusercontent.com/3928502/141797815-77a11cc4-f344-4913-ba7f-b978ba8c97f2.png">

I hope we will receive a more precise and final ROI but for now how difficult is it for you to extract the corresponding cityGML? Knowing that we might iterate one or two times on the exact value of the ROI.

let me know if you need more information from me

**Comment by DiegoVinasco** [comment]
@agrignard, I think this image is enough for now to extract the relevant CityGML data. I'll test cutting out the ROI with FME this week.

When we do have a precise ROI, having the 2 (or 4) bounding box coordinates that envelop the ROI in the ESPG:3946 coordinate reference system would be very helpful since that's the projection used in the metropole datasets.

**Comment by agrignard** [comment]
@DiegoVinasco here are the current (not sure it's the final one yet) of the lat and long of the ROI 
upperleft: 4,8742, 45,7735
upperright: 4,8834, 45,7735
lower right: 4,8834, 45,7650
lower left: 4,8742, 45,7650

**Comment by DiegoVinasco** [comment]
The CityGML dataset is created and available on [Nextcloud](https://partage.liris.cnrs.fr/index.php/f/667073694). The file alone (without any texture) is 30mb so I didn't upload it to the repository.

If you don't have access to the nextcloud, you can ask Gilles for permission, and/or I can make a read-only link.

I've also put a link in the [models readme](/ReAgent/models/Readme.md) for future reference.

I guess we can leave this issue open until the actual ROI is decided?

**Comment by agrignard** [comment]
Ok great news! Any screenshots?

Also I guess what we will need at some point is a UD_VIZ demo to be able to visualize this file. Maybe @vmachado can give us an help on this

**Comment by DiegoVinasco** [comment]
Yes, screenshot here:
![gratteciel 2018 citygml dataset](https://partage.liris.cnrs.fr/index.php/s/cDGs8LEY5k2XH4M/preview)

The demo will be done in #6 

I also moved the readme up a folder to [/ReAgent/Readme.md](/ReAgent/Readme.md) but if there is a better place to save the link, perhaps the wiki even, feel free to move it

**Comment by agrignard** [comment]
This issue can be closed as the Virtual ROI of the project has been identified here https://github.com/VCityTeam/UD_ReAgent_ABM/blob/master/ReAgent/includes/GratteCiel/Data_cc46/Emprise_500_1000.geojson (though it's different from the physical table as described in this issue https://github.com/VCityTeam/UD-Demo-Anthropocene-GratteCiel-/issues/10)
