### ISSUE TITLE
GAMA 1.9 Compatibility

### ISSUE THREAD

**Issue by agrignard** [VCityTeam/UD_ReAgent_ABM#30]
The boostrap.js has been changed accoding ot the work made with @hqnghi88 in this commit https://github.com/VCityTeam/UD_ReAgent_ABM/commit/20358f163e0de176c06b9bcad13b86da95ff6860

I am running the demo with the latest relaese of GAMA_1.9

However Iget  the following error in the JavaScript console when launching ```npm run debug``` and opening ```http://localhost:8000/debug.html```:
<img width="503" alt="Screenshot 2023-02-23 at 14 34 28" src="https://user-images.githubusercontent.com/3928502/220921846-06f47357-497c-42cb-9d31-7dddf078c4d5.png">

```
Uncaught (in promise) SyntaxError: Unexpected token 'W', "Wrong exp_"... is not valid JSON
    at JSON.parse (<anonymous>)
    at FileSource.parse [as parser] (GeoJsonParser.js:273:1)
    at FileSource.onLayerAdded (FileSource.js:219:1)
    at Layer.js:188:1
```

**Comment by hqnghi88** [comment]
https://github.com/VCityTeam/UD_ReAgent_ABM/pull/31#partial-pull-merging

**Comment by agrignard** [comment]
Working with the last GAMA release Alpha Version 1.9.0 (3508b348)
