### ISSUE TITLE
Define the number of lego for CityScope 

### ISSUE THREAD

**Issue by agrignard** [VCityTeam/UD_ReAgent_ABM#5]
A command has been made on this project for the Hanoi table, it woul dbe great to have also this sets in order to start the scanning

https://github.com/CityScope/CSL_Hanoi/issues/10

**Comment by CorentinGaut** [comment]
After some test with [UD-Legonizer](https://github.com/VCityTeam/UD-Legonizer) to create lego model. We need approximately 1500 Lego of differents size for a model of 4x4 lego tiles ( one tiles is 32x32 pick ).
All this information are export [here](https://github.com/VCityTeam/VCity/edit/master/Projects/Gratte_Ciel/Gratte_Ciel.md)

**Comment by agrignard** [comment]
Ok great starts.

Looking at the picture what you refer as the lego model is only the existing gratte ciel right? What do you think will be the number of lego for the hole "sites" currently described here (https://github.com/VCityTeam/UD_ReAgent_ABM/issues/3)

**Comment by CorentinGaut** [comment]
Yes the number will be for the hole "sites" because i calculate it for a model of 4x4 tiles and for the previous project "Part-dieu" we have ordered 1150 lego for 4x3 tiles. So i guess this will be fine but we can go to 2000 legos to be sure.

**Comment by agrignard** [comment]
For the hole site do you mean this one? (for me this is just the "gratte ciel")
<img width="830" alt="Screenshot 2021-11-16 at 14 47 27" src="https://user-images.githubusercontent.com/3928502/141997010-4bd4edb2-c484-4167-89ef-913312039a60.png">

What I mean by the hole site is this (Gratte Ciel + new project + surronding)
<img width="471" alt="Screenshot 2021-11-16 at 14 49 07" src="https://user-images.githubusercontent.com/3928502/141997260-d9c218a1-6953-4f62-bd0b-516132f06fa8.png">

**Comment by CorentinGaut** [comment]
For only Gratte Ciel it is approximately 900 legos, so maybe 1100 legos for the new projet will be good but its hard to estimate, it depend on the height of the new project's buildings and their surfaces

**Comment by agrignard** [comment]
Ok we will need to agree on this. 900 for Gratte Ciel, then 1100 for the new project but also what about the surrounfing part (the grey part in the previous picture,)

Hopefully we will provide you soon the cityGML file ones discussed with @DiegoVinasco related to #3

**Comment by DiegoVinasco** [comment]
@agrignard @CorentinGaut, I've uploaded the CityGML dataset to [Nextcloud](https://partage.liris.cnrs.fr/index.php/f/667073694) according to the [tentative ROI](https://github.com/VCityTeam/UD_ReAgent_ABM/issues/3#issuecomment-970162303)

**Comment by agrignard** [comment]
@CorentinGaut I got the information yesterday that the scale of the table is 1/500. Do we now have enough information to estimate the number of lego. To do so we also need to be sure we have the right cityGML. I am not sure we already identified it. 

@DiegoVinasco would it be possible to have a screenshot if the current cityGML you have?

**Comment by DiegoVinasco** [comment]
@agrignard yes, here is a link to the screenshot on nextcloud:
![gratteciel 2018 citygml dataset](https://partage.liris.cnrs.fr/index.php/s/cDGs8LEY5k2XH4M/preview)

**Comment by agrignard** [comment]
Ok great. @CorentinGaut are you able to use this model in Legotizer?

**Comment by CorentinGaut** [comment]
Yes ! i can use this file to simulate the model

**Comment by agrignard** [comment]
Awesome!

Do you think you can document in the same way you did but in this issue to keep track https://github.com/VCityTeam/VCity/edit/master/Projects/Gratte_Ciel/Gratte_Ciel.md the process and the final number 

You can put all the information here and I will later distill them in the WIKI if it's ok for you

**Comment by CorentinGaut** [comment]
![image](https://user-images.githubusercontent.com/32339907/143447901-215f5391-1cee-4955-a708-0ae30b90230b.png)
For this model i calculate : approx. 1300  legos with 16 tiles

**Comment by agrignard** [comment]
What is the Blue surface? We agree that the lego needs to represent the hole ROI which is meterialized in the cityGML

**Comment by CorentinGaut** [comment]
Okey mb. i will simulate for the whole gml model

**Comment by CorentinGaut** [comment]
![image](https://user-images.githubusercontent.com/32339907/143451176-ceb5f87e-d5f8-436d-9786-e111a11efd24.png)
 So with the whole it simulate this lego model ⬆️ 5 * 6 tiles of legos

And to create it we need approx. 2300 legos. I propose to order 2800 legos to be sure :

![image](https://user-images.githubusercontent.com/32339907/143451029-eb37d14f-20d5-4c6c-af85-6bb871845889.png)

**Comment by agrignard** [comment]
PERFECT!
