### ISSUE TITLE
Create a basic simple UD_VIZ visualizer demo

### ISSUE THREAD

**Issue by agrignard** [VCityTeam/UD_ReAgent_ABM#7]
Before to run let's walk. 

So before to work on a timelapse (issue #6) which might not be the priority anymore. Let's first try to visualise the gratte ciel as it is now (2018) in UD_VIZ.

@DiegoVinasco don't hesitate to point me to the right documentation link to to do so.

**Comment by DiegoVinasco** [comment]
@agrignard,
Yes, let's start by creating a 3DTiles dataset for the Villeurbanne district UD-Viz created with the "classic" approach which is to use the [cityGMLTo3DTiles pipeline](https://github.com/VCityTeam/cityGMLto3DTiles).

Normally, you should be able to in 3 steps:
1. Install Python >= 3.7 and Docker if you haven't already.
2. Clone the GitHub repo and install the dependencies using ["the hands-on method"](https://github.com/VCityTeam/cityGMLto3DTiles/tree/master/PythonCallingDocker#the-hands-on-method) to work in a virtual environment.
3. Configure and run the [static tiler workflow](https://github.com/VCityTeam/cityGMLto3DTiles/blob/master/PythonCallingDocker/Readme.md#running-the-static-tiler-workflow)
    - [configuration](https://github.com/VCityTeam/cityGMLto3DTiles/blob/master/PythonCallingDocker/Readme.md#static-case-configuration-step) should be set with `vintage = 2018` and `boroughs=[VILLEURBANNE]`

This will create a dataset much larger than our ROI but in the short term, the static tiler is more stable than the temporal counterpart so it will be easier to get a demo up and running.

I found an [old online demo](http://rict.liris.cnrs.fr/Demo_LyonFull_Villeurbanne_Bron_2015/UDV/UDV-Core/examples/DemoFull/Demo.html) that does used the static tiler to create a dataset for Lyon, Bron, and Villeurbanne in 2015 so I am more confident it should work for us as well.

**Comment by agrignard** [comment]
I started "the hands-on method" and it requires to install XCode which is like 5gb on Mac (I am fine with this but is there a lighter way to have a simple 3D model in UD_VIZ?) Is it mandatory to have XCode on Mac?

**Comment by agrignard** [comment]
Hi @DiegoVinasco I am trying to run the hands-on method I amnage to arrive until here
https://github.com/VCityTeam/cityGMLto3DTiles/tree/master/PythonCallingDocker#note-on-the-location-of-the-static-results

But I then get the following error:
`````
(venv) arno@Arnos-MBP DemoStatic % python3 run_workflow_static.py
100% [................................................] 4183628122 / 4183628122Traceback (most recent call last):
  File "/Users/arno/Projects/GitHub/cityGMLto3DTiles/PythonCallingDocker/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/arno/Projects/GitHub/cityGMLto3DTiles/PythonCallingDocker/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1276, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1322, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1271, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1031, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 969, in send
    self.connect()
  File "/Users/arno/Projects/GitHub/cityGMLto3DTiles/PythonCallingDocker/venv/lib/python3.10/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory
`````

**Comment by DiegoVinasco** [comment]
@agrignard, I asked @EricBoix, our other resident mac user and the error seems to be a fault in communicating with or launching a docker container. Could you check if the docker daemon is running on your PC ? Just run `docker ps` in the terminal.

It looks like you ended up using Python 3.10 installed from Brew, apparently this is the recommended way to run the pipeline on macos (and avoid using XCODE). I'll update the documentation.

It might be worth trying Python 3.7 as it was the version used to create the original pipeline and should be the most stable.

**Comment by agrignard** [comment]
Yep maybe something look strange with docker this is what I have with docker ps
`````
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
``````
for python it was written 3.7 or greater. Maybe 3.10 is ok

**Comment by DiegoVinasco** [comment]
Normally the docker daemon should start automatically as a service. When looking online everyone seems to be recommending installing docker with cask for "newer" macs :

https://stackoverflow.com/questions/40523307/brew-install-docker-does-not-include-docker-engine

I'm not sure what the limit is for an "old" mac but it looks like they don't properly support virtualization natively and actually run on VirtualBox which I'm assuming won't work with the pipeline.

**Comment by DiegoVinasco** [comment]
I managed to get the data pipeline to work (with a bit of manual effort). I've posted the Villeurbanne 2018 static tileset online [on the dataset file server](https://dataset-dl.liris.cnrs.fr/three-d-tiles-lyon-metropolis/Villeurbanne_2018_TileSet/)

For the next steps to launch a basic UD-Viz demo :
1. Follow the [UD-Viz-Template](https://github.com/VCityTeam/UD-Viz-Template) instructions for setting up a basic demo
2. Make sure to edit the [config file](https://github.com/VCityTeam/UD-Viz-Template/blob/master/assets/config/config.json) so that the 3DTilesLayers settings point to the online tileset. For example:
```
...
"3DTilesLayers": [
    {
      "id": "Villeurbanne",
      "url": "https://dataset-dl.liris.cnrs.fr/three-d-tiles-lyon-metropolis/Villeurbanne_2018_TileSet/tileset.json",
      "color": "0xFFFFFF"
    },
  ],
...
```

Once that is working, we can take a look at #6

**Comment by DiegoVinasco** [comment]
@agrignard I think I may have a work around for the webpack version conflict.

When working with the dockerized version of UD-Viz-Template, the [dockerfile expressly uses v2.32.4](https://github.com/VCityTeam/UD-Viz-Template-docker/blob/60e4a9635dc1a9ef81e2a6e22e2880fe559ff0dc/DemoFull-SimpleServer/Dockerfile#L27). When you clone UD-Viz-Template, try this :
```bash
git clone --branch v2.32.4 https://github.com/VCityTeam/UD-Viz-Template.git
```

**Comment by agrignard** [comment]
Great we have now the Hell World in UD_ReAgent_ABM/UD-Viz-ReAgent-GratteCiel

Thank you @DiegoVinasco 

We can now close this issue as more atomic one will appear later 


<img width="621" alt="Screenshot 2021-12-07 at 17 04 12" src="https://user-images.githubusercontent.com/3928502/145063965-c4a2beeb-5b1d-414b-a4b5-6e14db977780.png">
